### ISSUE TITLE
Question about Yelp File

### ISSUE THREAD

**Issue by wby1999** [ronaldseoh/atsc_prompts#5]
Hello. Can you provide the file "restaurantIDs.txt"? Thank you.

**Comment by ronaldseoh** [comment]
I'm very sorry for the delay. Here's the file:
[restaurantIDs.txt](https://github.com/ronaldseoh/atsc_prompts/files/7748186/restaurantIDs.txt)

**Comment by wby1999** [comment]
Thank you very much.
