### ISSUE TITLE
Yelp Review Dataset for PLM domain adaptation

### ISSUE THREAD

**Issue by jjapagguri** [ronaldseoh/atsc_prompts#6]
Hello I am really interested in your paper and especially thank you for opening your code for replication.
I was trying to study your method and in the process, I was stuck in further pre-training BERT with Yelp Review dataset.

At your paper, it was said that you extracted review dataset related to restaurant, and I think it is the "restaurantIDs.txt" if I am right. However, I cannot find the ID text file in your repository, so can I know the source or the method you extracted restaurant IDs??

Thank you for your work!
Best regards,
kyuri.

**Comment by jjapagguri** [comment]
Oh I found the closed issue now!!
Thank you.

**Comment by ronaldseoh** [comment]
Hi Kyuri,

Sorry for the late reply! Let me know if you encounter any other issues.

Ronald
